os: linux
dist: bionic

language: ruby
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - ruby-head

jobs:
  allow_failures:
    - rvm: ruby-head

before_install:
  - gem install bundler

script:
  - bundle exec rspec